---

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - --log.level=DEBUG
      - --providers.docker=true
      # Set up an insecure listener which can be used behind caddy
      - --entrypoints.web.address=:80
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: netstat -ptan | grep -E "80.*LISTEN" || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
      labels:
        - "traefik.http.routers.dashboard.rule=Host(`traefik.local`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=web"

  gluetun:
    # See more: https://github.com/qdm12/gluetun-wiki
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: ./env/gluetun.env
    volumes:
      - gluetun:/gluetun
    ports:
      - "50000:50000/tcp"
      - "50000:50000/udp"

include:
  - bittorrent-compose.yml
  - arr-compose.yml
#  - plex-compose.yml
#  - jellyfin-compose.yml

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true